apiVersion: v1 
kind: Pod
metadata: 
    name: docker
spec: 
    containers: 
    - name: docker 
      image: docker 
      command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
      env: 
        - name: DOCKER_HOST 
          value: tcp://localhost:2375
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
             name: docker-secret
             key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: password 
        - name: IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: docker-image
              key: image 
        - name: TAG
          valueFrom:
            configMapKeyRef:
              name: docker-image
              key: version  
      lifecycle:
        postStart:
          exec:
           command:
           - sh
           - -c
           - > 
             docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
             sleep 10; cd tmp; docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$TAG .;docker push $DOCKER_USERNAME/$IMAGE_NAME:$TAG          
    - name: dind-daemon 
      image: docker:1.12.6-dind 
      securityContext: 
        privileged: true 
      volumeMounts: 
      - name: docker-graph-storage 
        mountPath: /var/lib/docker
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
     
     
      
        
